[build]
  command = "npm install && npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[cache]
  # Cache node_modules and Next.js cache to speed up builds
  paths = [
    "node_modules",
    ".next/cache"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[plugins]]
#   package = "@netlify/plugin-cache"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
